// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM5MiwIxanAn2TjlXU7Dy6iCHUqE-d0ZA',
    appId: '1:119821773199:web:7cc5bf79d5b9b5f5dd03fa',
    messagingSenderId: '119821773199',
    projectId: 'mediconnect-4b155',
    authDomain: 'mediconnect-4b155.firebaseapp.com',
    storageBucket: 'mediconnect-4b155.firebasestorage.app',
    measurementId: 'G-TLQWZMZ9N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyOMSHiwIxanAnZTjlXU7Dy6iCHUqE-d8ZA',
    appId: '1:119821773199:android:7cf59ad2bacdcce2dd83fa',
    messagingSenderId: '119821773199',
    projectId: 'mediconnect-4b155',
    authDomain: 'mediconnect-4b155.firebaseapp.com',
    storageBucket: 'mediconnect-4b155.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyOMSHiwIxanAnZTjlXU7Dy6iCHUqE-d8ZA',
    appId: '1:119821773199:ios:7cf59ad2bacdcce2dd83fa',
    messagingSenderId: '119821773199',
    projectId: 'mediconnect-4b155',
    authDomain: 'mediconnect-4b155.firebaseapp.com',
    storageBucket: 'mediconnect-4b155.firebasestorage.app',
    iosBundleId: 'com.example.mediConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyOMSHiwIxanAnZTjlXU7Dy6iCHUqE-d8ZA',
    appId: '1:119821773199:ios:7cf59ad2bacdcce2dd83fa',
    messagingSenderId: '119821773199',
    projectId: 'mediconnect-4b155',
    authDomain: 'mediconnect-4b155.firebaseapp.com',
    storageBucket: 'mediconnect-4b155.firebasestorage.app',
    iosBundleId: 'com.example.mediConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyOMSHiwIxanAnZTjlXU7Dy6iCHUqE-d8ZA',
    appId: '1:119821773199:web:7cf59ad2bacdcce2dd83fa',
    messagingSenderId: '119821773199',
    projectId: 'mediconnect-4b155',
    authDomain: 'mediconnect-4b155.firebaseapp.com',
    storageBucket: 'mediconnect-4b155.firebasestorage.app',
    measurementId: 'G-TLQWZMZ9N2',
  );
}
